### ISSUE TITLE
Erro na ordenação: Usando caracteres especiais

### ISSUE THREAD

**Issue by thiagojacinto** [alvesmog/unit-spw-4-avaliacao#3]
Como o pop() muda o valor para a string 'vazio', ao usar cores com acentuação (ex: Índigo), a ordenação dá errado.

Exemplo:
```java
gavetaEmPilha.pop();
```

Camisas na gaveta: // Após retirar um item
[Rosa, Amarelo, Roxo, Anil, Magenta, Limão, Magenta, Terracota, Índigo, **vazio**]

Camisas ordenadas por nome: 
[Amarelo, Anil, Limão, Magenta, Magenta, Rosa, Roxo, Terracota, **vazio**, ***Índigo***]

**Comment by thiagojacinto** [comment]
Levar em consideração a ordenação de acordo com o valor na tabela [ASCII](https://pt.wikipedia.org/wiki/Ficheiro:ASCII-Table-wide.svg).

**Comment by thiagojacinto** [comment]
Usei um char de maior valor na tabela ASCII => `"·"`, que o método pop() da Pilha usa para substituir o valor da variável retirada.

Commit [resolvido](https://github.com/alvesmog/unit-spw-4-avaliacao/commit/7b9338d4bb5230bfefa248ec803e397b4ce1b7b7). ☑️

**Comment by alvesmog** [comment]
Boa solução. Funciona para todos os casos de acentuação? 

Entendo que "a" != "á". E na tabela ASCII, "a" está na posição 97 e "á" na 160.

**Comment by thiagojacinto** [comment]
> Boa solução. Funciona para todos os casos de acentuação?

Funciona sim, pois esse ponto tá na posição 250 da tabela ASCII. Chama pouca atenção e garante que nenhuma letra, com ou sem acentuação, maiúscula ou minúscula seja ordenada na sua frente.

Outra opção que pensei era colocar uma verificação lá no método de ordenação para que ordenasse até o topo. Assim não chegaria não teria como comparar com 'vazio' nunca, pois o topo está sempre uma posição abaixo após usar o `pop()`. Mas não testei...
